### ISSUE TITLE
wot no code?

### ISSUE THREAD

**Issue by harry-wood** [theodi/open-data-barometer-viz#6]
The repo has no code in it

**Comment by JeniT** [comment]
see [gh-pages branch](https://github.com/theodi/open-data-barometer-viz/tree/gh-pages). Some would argue that the master branch should be deleted in repos like this.

**Comment by harry-wood** [comment]
Ah yeah. Didn't spot the branch. BTW  I found the repo by searching on github because. It's not linked from the page anywhere is it?
